### ISSUE TITLE
tbx file upload crash

### ISSUE THREAD

**Issue by biounix** [watermint/toolbox#418]
**Describe the bug**

Crash.

**To Reproduce**

1. Run command `tbx file upload -local-path file -dropbox-path /test`
2. See error

**Screenshots, or log snippets**

> Testing network connection...
> Done
> 
> ERROR	Recipe failed with an error	{"error": "During db.vlog.open: Error while creating log file in valueLog.open: Mmap value log file. Path=/home/user/.toolbox/jobs/20200803-130752.001/kvs/rp_writer_sorted-skipped/000000.vlog. Error=cannot allocate memory", "errorVerbose": "Mmap value log file. Path=/home/user/.toolbox/jobs/20200803-130752.001/kvs/rp_writer_sorted-skipped/000000.vlog. Error=cannot allocate memory\nError while creating log file in valueLog.open\ngithub.com/dgraph-io/badger/v2/y.Wrapf\n\t/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/y/error.go:82\ngithub.com/dgraph-io/badger/v2.(*valueLog).open\n\t/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/value.go:1101\ngithub.com/dgraph-io/badger/v2.Open\n\t/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:380\ngithub.com/watermint/toolbox/essentials/kvs/kv_storage_impl.(*badgerWrapper).openWithPath\n\t/go/src/github.com/watermint/toolbox/essentials/kvs/kv_storage_impl/storage.go:122\ngithub.com/watermint/toolbox/essentials/kvs/kv_storage_impl.(*badgerWrapper).init\n\t/go/src/github.com/watermint/toolbox/essentials/kvs/kv_storage_impl/storage.go:151\ngithub.com/watermint/toolbox/essentials/kvs/kv_storage_impl.(*badgerWrapper).Open\n\t/go/src/github.com/watermint/toolbox/essentials/kvs/kv_storage_impl/storage.go:54\ngithub.com/watermint/toolbox/infra/report/rp_writer_impl.(*Sorted).Open\n\t/go/src/github.com/watermint/toolbox/infra/report/rp_writer_impl/sorted.go:92\ngithub.com/watermint/toolbox/infra/report/rp_writer_impl.(*cascadeWriter).Open\n\t/go/src/github.com/watermint/toolbox/infra/report/rp_writer_impl/cascade.go:75\ngithub.com/watermint/toolbox/infra/report/rp_model_impl.(*TransactionReport).Open\n\t/go/src/github.com/watermint/toolbox/infra/report/rp_model_impl/transaction.go:65\ngithub.com/watermint/toolbox/ingredient/file.(*Upload).Exec\n\t/go/src/github.com/watermint/toolbox/ingredient/file/upload.go:274\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.ExecSpec.func1\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:39\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.DoSpec\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:55\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.ExecSpec\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:38\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.Exec\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:15\ngithub.com/watermint/toolbox/recipe/file.(*Upload).Exec\n\t/go/src/github.com/watermint/toolbox/recipe/file/upload.go:32\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.ExecSpec.func1\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:39\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.DoSpec\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:55\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.ExecSpec\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:38\ngithub.com/watermint/toolbox/infra/control/app_bootstrap.(*bsImpl).Run\n\t/go/src/github.com/watermint/toolbox/infra/control/app_bootstrap/bootstrap.go:212\nmain.run\n\t/go/src/github.com/watermint/toolbox/tbx.go:30\nmain.main\n\t/go/src/github.com/watermint/toolbox/tbx.go:34\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_386.s:1337\nDuring db.vlog.open\ngithub.com/dgraph-io/badger/v2/y.Wrapf\n\t/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/y/error.go:82\ngithub.com/dgraph-io/badger/v2.Open\n\t/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:381\ngithub.com/watermint/toolbox/essentials/kvs/kv_storage_impl.(*badgerWrapper).openWithPath\n\t/go/src/github.com/watermint/toolbox/essentials/kvs/kv_storage_impl/storage.go:122\ngithub.com/watermint/toolbox/essentials/kvs/kv_storage_impl.(*badgerWrapper).init\n\t/go/src/github.com/watermint/toolbox/essentials/kvs/kv_storage_impl/storage.go:151\ngithub.com/watermint/toolbox/essentials/kvs/kv_storage_impl.(*badgerWrapper).Open\n\t/go/src/github.com/watermint/toolbox/essentials/kvs/kv_storage_impl/storage.go:54\ngithub.com/watermint/toolbox/infra/report/rp_writer_impl.(*Sorted).Open\n\t/go/src/github.com/watermint/toolbox/infra/report/rp_writer_impl/sorted.go:92\ngithub.com/watermint/toolbox/infra/report/rp_writer_impl.(*cascadeWriter).Open\n\t/go/src/github.com/watermint/toolbox/infra/report/rp_writer_impl/cascade.go:75\ngithub.com/watermint/toolbox/infra/report/rp_model_impl.(*TransactionReport).Open\n\t/go/src/github.com/watermint/toolbox/infra/report/rp_model_impl/transaction.go:65\ngithub.com/watermint/toolbox/ingredient/file.(*Upload).Exec\n\t/go/src/github.com/watermint/toolbox/ingredient/file/upload.go:274\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.ExecSpec.func1\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:39\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.DoSpec\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:55\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.ExecSpec\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:38\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.Exec\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:15\ngithub.com/watermint/toolbox/recipe/file.(*Upload).Exec\n\t/go/src/github.com/watermint/toolbox/recipe/file/upload.go:32\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.ExecSpec.func1\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:39\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.DoSpec\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:55\ngithub.com/watermint/toolbox/infra/recipe/rc_exec.ExecSpec\n\t/go/src/github.com/watermint/toolbox/infra/recipe/rc_exec/exec.go:38\ngithub.com/watermint/toolbox/infra/control/app_bootstrap.(*bsImpl).Run\n\t/go/src/github.com/watermint/toolbox/infra/control/app_bootstrap/bootstrap.go:212\nmain.run\n\t/go/src/github.com/watermint/toolbox/tbx.go:30\nmain.main\n\t/go/src/github.com/watermint/toolbox/tbx.go:34\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_386.s:1337"}
> Operation failed with an error: During db.vlog.open: Error while creating log file in valueLog.open: Mmap value log file. Path=/home/user/.toolbox/jobs/20200803-130752.001/kvs/rp_writer_sorted-skipped/000000.vlog. Error=cannot allocate memory

**Desktop (please complete the following information):**
 
- OS: Ubuntu 16.04
 - toolbox Version 72.4.544

**Additional context**

Other commands such as `tbx sharedlink list` work as expected.

**Comment by watermint** [comment]
@biounix Thank you for the report. I'll figure out the issue and fix in the next release.

**Comment by watermint** [comment]
fix confirmed with the VM:
```
$ uname -a
Linux ubuntu32 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:01:15 UTC 2019 i686 i686 i686 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
```

**Comment by biounix** [comment]
Thanks a lot!
