### ISSUE TITLE
Switch to initiate API key for the subcommand (member list, member delete, member suspend)

### ISSUE THREAD

**Issue by thessellund** [watermint/toolbox#566]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In creating automation, we'd like to be able to generate the API request without any action. In particular this would be useful for the first 'member delete' command. If we could have something like 'tbx member delete -createapi' then we can initiate the request, allow the action and now that we have the key and throw that in a script/loop to follow up on the action required.

**Describe alternatives you've considered**
The Alternative is to run the command against a single user first in order to create the API request, then run it against the remaining users in a script.

**Additional context**

**Comment by watermint** [comment]
Here is the new command. 
https://toolbox.watermint.org/commands/config-auth-delete.html
