### ISSUE TITLE
Unable to import a 2MB file

### ISSUE THREAD

**Issue by bingvillamor** [watermint/toolbox#570]
Hi,
I'm trying out 'tbx' on a 2MB file.
Command used is"tbx services google sheets sheet import -id 1M3n9tA378VY3TXrjU2LENMD3NxcJCG3UvxEDTZnytsI -range Sheet1! -data OSSBooking_test.csv"
Error is 
Unable to read file `OSSBooking_test.csv' due to an error record on line 23: wrong number of fields
Unable to read file `OSSBooking_test.csv` due to an error record on line 23: wrong number of fields
The command finished: 4.343s
Operation failed with an error: record on line 23: wrong number of fields"

Can you help me where to look and what to do as I'm hoping tbx is the solution to my dilemma when importing CSV files greater than 2MB and the file contains all columns.

Yours,

Bing

**Comment by watermint** [comment]
Thank you for reporting. This program, `tbx`, uses https://pkg.go.dev/encoding/csv for parsing CSV. That means the `tbx` expect the file formatted with [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180) compliant CSV file.
I believe it's not a matter of file size. I frequently import CSV > 2MB without an error.

Please verify your CSV file line number 23.
