### ISSUE TITLE
Create Google Sheets in specific folder (Folder ID)

### ISSUE THREAD

**Issue by thessellund** [watermint/toolbox#571]
**Describe the solution you'd like**
It would be nice when using the google sheet create command if you could also tell it where to create the sheet. I'm looking to be able to create the Sheet in a specific folder that is already shared to a particular group so when the sheet is created, it is automatically shared with the correct people. This will be useful for uploading/creating logs from the TBX command in a centralized location for the team and for audit tracking.

**Describe alternatives you've considered**

**Additional context**

**Comment by watermint** [comment]
Thank you for the request. I'll check the Google API how I can implement it.

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by watermint** [comment]
Because of full deprecation of Google commands (#835), this request also closed without release.
Thanks
