### ISSUE TITLE
Suppress all job files, just output to CLI

### ISSUE THREAD

**Issue by ImportTaste** [watermint/toolbox#572]
Dropbox is unwieldy without the use of its API, and this seemed like the most feature-complete tool I could find. I don't really need all the logs and reports for the operation I have in mind, which is a scheduled task that parses the json from the command line output through jq.

Could you add a new common parameter parameter to suppress the creation of all job files associated with commands it's used on?

**Comment by watermint** [comment]
Thank you for the request. I'll add the option in the future release.
For the temporary workaround, there is a configuration that automatically removes older job files (+7days old) at job start.

```
tbx config enable -key ingredient.bootstrap.opt_in_feature_autodelete

watermint toolbox 98.8.1112
===========================

© 2016-2021 Takayuki Okazaki
Licensed under open source licenses. Use the `license` command for more detail.

Removing old job data if it found.
Auto deletes old job history data if a job is older than 7 days.
Automatic delete may cause loss of your data. Please keep backup those files before enabling this feature if you needed.
YES     <--- "Type YES"
```

Hope this will also helps.

**Comment by ImportTaste** [comment]
@watermint I'm not getting any output using `tbx sharedlink file list -url URLHERE -retain-job-data none -output json`

When using the same command, just without `-retain-job-data none` it works just fine.
