### ISSUE TITLE
Command for deleting members one by one

### ISSUE THREAD

**Issue by RobertHild** [watermint/toolbox#573]
**Question about:**
- [x] Specific command: Please specify command [ member delete ]
- [ ] Instruction / document
- [ ] Other

**Additional context**
Is there any way to delete members in Dropbox Business one-by-one (comparable to suspend / unsuspend member commands) in order to set individual destination members?
Unfortunately, our login names for Dropbox Business differ from the normal e-mail-addresses.
Therefore many of our users register for a second business account in our team.
We would like to remove those duplicates and transfer the data to the 'correct' account.

Looking forward to your reply, kind regards
Robert

P.S.: Sorry, if this issue may be in the wrong category - perhaps ist should be tagged as feature request?

**Comment by watermint** [comment]
Hi. Thank you for the question.

Here is the manual for `member delete`. But currently, the command only accepts CSV file to delete the member. And the CSV file does not support individual destination member.
https://toolbox.watermint.org/commands/member-delete.html

If you want to delete a member one-by-one, you can pass CSV data through standard input by passing `-` to the `-file` argument.

```
echo someone@example.com | tbx member delete -file - -transfer-dest-member dest@example.com
```

**Comment by RobertHild** [comment]
Hi, thank you very much for your fast reply.
So when I as an admin want to delete member "someone@domain1.com" and transfer his files to his account "someone@domain2.com" on a Windows client, the command line is

echo someone@domain1.com | .\tbx.exe member delete -file - -transfer-dest-member someone@domain2.com -transfer-notify-admin-email-on-error admin@domain2.com

Is this correct? Or are there other specifications for Windows clients?

Looking forward to yor reply, kind regards,
Robert 

P.S.: Are there any changes concerning this command planned in the upcoming versions of watermint?

**Comment by RobertHild** [comment]
@watermint - sorry for any inconvenience but did I get your last comment right?

Is this the correct command in toolbox to delete a single user and to transfer his files to another account?

echo someone@domain1.com | .\tbx.exe member delete -file - -transfer-dest-member someone@domain2.com -transfer-notify-admin-email-on-error admin@domain2.com

Looking forward to your reply, kind regards,
Robert

**Comment by watermint** [comment]
Hi. I believe that should work. There is no immediate plan to changing command related this. Please reopen the issue if you got unexpected result. Thanks

**Comment by RobertHild** [comment]
Hi,
thank you very much - I just tested it with an account and it seems to work.
If we meet some unexpected results with further users, I will contact you again.

Just one additional info on the command line mentioned above:
echo user@domain1.co**m|** .\tbx.exe member delete -file - -transfer-dest-member user@domain2.com -transfer-notify-admin-email-on-error admin@domain2.com

At least on my Windows client, there must be no space between the echo command and the pipe, otherwise the command results in a failure stating

Error: Error in call to API function "team/members/get_info": request body: members: 'user@domain1.com ' did not match pattern '^['#&A-Za-z0-9._%+-]+@[A-Za-z0-9-][A-Za-z0-9.-]*\.[A-Za-z]{2,15}$'
