### ISSUE TITLE
Report: teamfolder file size - size in KB / MB?

### ISSUE THREAD

**Issue by RobertHild** [watermint/toolbox#587]
**'size' in teamfolder file size report :**
- [x] Specific command: teamfolder file size

**Additional context**
In which unit is the 'size' indication given in the report? (KB, MB?)

Looking forward to your reply, thank you and kind regards,
Robert

**Comment by RobertHild** [comment]
@watermint - sorry for bothering you, but would you mind to give me a short feedback on this topic?

Looking forward to your reply, kind regards,
Robert

**Comment by watermint** [comment]
Hi. Sorry for the delayed response.
Currently, I don't have plans to add a human readable size (KB, MB) column for this specific report.
But for the future plan, I'll refresh all reporting infrastructure to include the option to change units.
Thanks

**Comment by RobertHild** [comment]
Ok, thank you - i.e. the existing column 'size' in the report is _not_ the actual size of the team folder?
![image](https://user-images.githubusercontent.com/93777837/154018896-8052c569-7b95-4d9a-bdc0-2da0730eca67.png)

**Comment by watermint** [comment]
I see. The size 28,248,048,654 is about 26TiB. It is roughly 66MB for each file.
You can see folder size with the instruction below.
https://help.dropbox.com/accounts-billing/space-storage/file-size

If it far differ from the size, it should be a bug. Please let me know if it was a bug.

**Comment by RobertHild** [comment]
Thank you very much for providing me with the help center article.
I displayed the size column an admin console for Team folders and the folder from my example has about 26,3 GB.

Kind regards,
Robert

**Comment by watermint** [comment]
Hi. My prior comment had a miscalculation. 28,248,048,654 bytes = 28.25 GB = 26.3 GiB.

**Comment by RobertHild** [comment]
Thanks for clarification.
