### ISSUE TITLE
"Error:unspecified_transfer_admin_id" when deleting user by "tbx member delete -file userlist.txt -transfer-dest-member admin@mydomain.com"

### ISSUE THREAD

**Issue by huwgeric** [watermint/toolbox#593]
(Thank you for developing this tool)

Description:
I tried to delete my team users listed in a csv file and transfer content to an admin account:
tbx member delete -file userlist.txt -transfer-dest-member admin@mydomain.com

I got error: "Error: unspecified_transfer_admin_id"

| status  | reason                                 | input.email                | result |
|---------|----------------------------------------|----------------------------|--------|
| Failure | Error: unspecified_transfer_admin_id/. | user1@mydomain.com         |        |

I can manually delete the account listed in csv file and transfer its file to "admin@mydomain.com"

1. Run command tbx member delete -file userlist.txt -transfer-dest-member admin@mydomain.com
2. See error: Error: unspecified_transfer_admin_id

**Expected behavior**
The account should be deleted, and Dropbox content should be transferred to "admin@mydomain.com"

**Desktop (please complete the following information):**
 - OS: Window2019 server
 - toolbox Version 102.8.1164

**Additional context**
Dropbox business account

**Comment by huwgeric** [comment]
I got same error when I tried to delete a single user:
echo user1@mydomain.com|tbx member delete -file - -transfer-dest-member admin@mydomain.com

User can be successfully deleted if I don't specify option "-transfer-dest-member"
tbx member delete -file userlist.txt

**Comment by watermint** [comment]
@huwgeric Sorry for delayed response.
Please try adding the option `-transfer-notify-admin-email-on-error` like below
```
echo [user1@mydomain.com](mailto:user1@mydomain.com)|tbx member delete -file - -transfer-dest-member [admin@mydomain.com](mailto:admin@mydomain.com) -transfer-notify-admin-email-on-error [admin@mydomain.com](mailto:admin@mydomain.com)
```
