### ISSUE TITLE
Pass local path to tbx

### ISSUE THREAD

**Issue by MartinDelille** [watermint/toolbox#594]
I wondered if it would be possible to pass the local path of file instead of giving the whole absolute dropbox file.

For example, let's say I want to share /Users/martin/Dropbox/screenshots/joker.png, I currently need to type `tbx sharedlink create -path /screenshots/joker.png`. I would be easier to to `cd ~/Dropbox/screenshots` then `tbx sharedlink create joker.png` to benefit local autocompletion.

**Question about:**
- [ ] Specific command: Please specify command [ ]
- [ ] Instruction / document
- [x] Other

**Comment by watermint** [comment]
Hi. Thank you for the feedback.
Unfortunately, it's technically difficult in two areas.

1. distinguish local path v. dropbox path. It should be done with while grammar refresh of commands.
2. authenticated dropbox account information. Dropbox creates the info file in `.dropbox/info.json`. But that does not contains account information (e.g. email address). Toolbox authenticate with Dropbox when you first run. But that credential potentially different if you have multiple accounts.

Until those resolution. I'll keep this issue as closed. I'll reopen and implement when found any solutions of those two areas.
Thanks
