### ISSUE TITLE
Team Folder Upload

### ISSUE THREAD

**Issue by KoenWindey** [watermint/toolbox#597]
**Question about: Uploading a file / folder**
- [ ] Specific command: file sync up []

Hi, I was wondering if it is possible to upload to a Team Folder? I have tried a few options, and it seems that I can list files/folder in the Team space, using the Business commands. But I cannot find anywhere how to upload to a team folder? Where do you define the root folder? I'm referring to this DBX guide: https://developers.dropbox.com/dbx-team-files-guide

Tnx
K

**Comment by watermint** [comment]
It's possible if you have access to the team folder.
The command `file sync up` uploads file into any path (including team folders) of you have mounted on your account.
In other words, it's not possible to upload if you don't have write access to the team folder.
