### ISSUE TITLE
`team content legacypaper export` does not work (need to change the endpoint)

### ISSUE THREAD

**Issue by watermint** [watermint/toolbox#674]
The command `team content legacypaper export` uses the endpoint content.dropboxapi.com, but the this APi exceptionally using 'api.dropboxapi.com' as content download endpoint.

**Comment by LucasOnfroyiAdvize** [comment]
Hi,
I need to use this feature and your tool is the only way to do what I want, do you know if there is a workaround or if the fix is simple enough for me to do ?
Thank you in advance,

**Comment by watermint** [comment]
@LucasOnfroyiAdvize 
Hi, there is no workaround this time on your side.
I'll try updating tool when I secure my time to fix.
I'll let you know when the version with fix released.
Thanks

**Comment by watermint** [comment]
Hi @LucasOnfroyiAdvize ,
I created the fix but I can't test this because I have no test account of legacy paper.
I hope the [new release](https://github.com/watermint/toolbox/releases/latest) solved your issue.

**Comment by LucasOnfroyiAdvize** [comment]
It worked perfectly, thank you very much for the fix
