### ISSUE TITLE
"error":"bad server response"

### ISSUE THREAD

**Issue by nevch1983** [watermint/toolbox#675]
**Describe the bug**
I can't authenticate and get an ""error":"bad server response" in my report logs, and I am using the latest version of watermint.

This is related to issue https://github.com/watermint/toolbox/issues/670

<img width="563" alt="Screen Shot 2022-12-02 at 11 03 34 AM" src="https://user-images.githubusercontent.com/31445394/205336091-d6b71771-2fa0-4408-9c44-37e5d432cae4.png">

**Comment by watermint** [comment]
@nevch1983 Could you try with the latest version?
Your version is 111, but 113 is the latest.
https://github.com/watermint/toolbox/releases/tag/113.8.795

**Comment by nevch1983** [comment]
it worked! thanks!
