### ISSUE TITLE
Processing special characters in group batch delete 

### ISSUE THREAD

**Issue by RobertHild** [watermint/toolbox#697]
Being an international company, there is no restriction for our users, e.g. when naming folders or groups. We tried to clear our group list by deleting empty groups by using _-group batch delete_ command and we met the issue that groups with special characters, e.g. German umlauts (ä, ö, ü) couldn't be processed by Watermint so that we had to delete those groups manually.

**Describe the solution you'd like**
Would it be possible to process special groups as well? Is there any way to format the CSV-file so that Watermint can process all groups?

Looking forward to your reply, kind regards,
Robert

**Comment by watermint** [comment]
@RobertHild Hi. Sorry for delayed response.
Both watermint and Dropbox supports international characters such as umlauts. But you need to use UTF-8 encoding for input file. Please try below steps.

For Windows.
1. Open Notepad and open your file.
2. Go to File > Save As... and choose UTF-8 under Encoding
3. Overwrite

**Comment by RobertHild** [comment]
@watermint Thank you very much! :-)
