### ISSUE TITLE
-skip-logging doesn't skip logging

### ISSUE THREAD

**Issue by joshuascottpaul** [watermint/toolbox#729]
**Describe the bug**
a job folder wih csv json oand xlsx is still created even with "-skip-loggin"

**To Reproduce**
sudo /usr/bin/tbx file list -path /neocode -auth-database "/home/neocode/.toolbox/secrets/secrets.db" -workspace /home/neocode/Logs/ -skip-logging

**Expected behavior**
no log folders

**Screenshots, or log snippets**
neocode@marion-fms20:~$ sudo /usr/bin/tbx file list -path /neocode -auth-database "/home/neocode/.toolbox/secrets/secrets.db" -workspace /home/neocode/Logs/ -skip-logging

watermint toolbox 119.8.866
===========================

© 2016-2023 Takayuki Okazaki
Licensed under open source licenses. Use the `license` command for more detail.

Testing network connection...
Done

| tag    | name          | path_display           | client_modified      | server_modified      | size   |
|--------|---------------|------------------------|----------------------|----------------------|--------|
| folder | documents     | /neocode/documents     |                      |                      | 0      |
| folder | quotes        | /neocode/quotes        |                      |                      | 0      |
| folder | invoices      | /neocode/invoices      |                      |                      | 0      |
| folder | payments      | /neocode/payments      |                      |                      | 0      |
| folder | credit.notes  | /neocode/credit.notes  |                      |                      | 0      |
| folder | debit.memos   | /neocode/debit.memos   |                      |                      | 0      |
| file   | documents (1) | /neocode/documents (1) | 2023-01-09T19:56:25Z | 2023-01-09T19:56:26Z | 120578 |
| file   | documents (2) | /neocode/documents (2) | 2023-01-09T20:00:34Z | 2023-01-09T20:00:34Z | 120578 |

The report generated: /home/neocode/Logs/jobs/20230708-154902.XYA/report/file_list.csv
The report generated: /home/neocode/Logs/jobs/20230708-154902.XYA/report/file_list.json
The report generated: /home/neocode/Logs/jobs/20230708-154902.XYA/report/file_list.xlsx

**Desktop (please complete the following information):**
ubuntu 22

watermint toolbox 119.8.866

**Comment by watermint** [comment]
Hi @joshuascottpaul ,
Thank you for reporting. But this is not a bug.

The option `-skip-logging` will not create logs `jobs/yyyyMMdd-HHmmss.xxx/logs/*`.
But will not skip generate reports (.csv, .xlsx, .json).
If you don't need those files, please use the option `-retain-job-data none`.
This will delete all job data on completion.

**Comment by joshuascottpaul** [comment]
thank you!

note - i had to specify a valid workspace space path - it create empty secrets and logs folders
