### ISSUE TITLE
file list -path json returned fails to parse

### ISSUE THREAD

**Issue by joshuascottpaul** [watermint/toolbox#737]
**Describe the bug**
json returned fails to parse

**To Reproduce**
1. run command tbx list -path / 
2. specifically /usr/bin/tbx file list -path / -auth-database /opt/FileMaker/FileMaker\ Server/Data/Documents/.toolbox/secrets/secrets.db -workspace /opt/FileMaker/FileMaker\ Server/Data/Documents/.toolbox/workspace/ -skip-logging -retain-job-data none -output json
3. json returned fails to parse - has double }}

Parse error on line 1:
...no_access": false}}{".tag": "folder", "
----------------------^
Expecting 'EOF', '}', ',', ']', got '{'

4. run command tbx list -path /neocode/quotes
5. specifically /usr/bin/tbx file list -path /neocode/quotes -auth-database /opt/FileMaker/FileMaker\ Server/Data/Documents/.toolbox/secrets/secrets.db -workspace /opt/FileMaker/FileMaker\ Server/Data/Documents/.toolbox/workspace/ -skip-logging -retain-job-data none -output json
6. json returned has single }

Parse error on line 1:
...234d113f8eaae7a71"}{".tag": "file", "na
----------------------^
Expecting 'EOF', '}', ',', ']', got '{'

**Expected behavior**
json parses

**Screenshots, or log snippets**
If applicable, add screenshots or log snippets to help explain your problem.

**Desktop (please complete the following information):**
 - OS: linux
 - toolbox Version  119.8.866

**Additional context**
[json reply from tbx file list --path.txt](https://github.com/watermint/toolbox/files/12264108/json.reply.from.tbx.file.list.--path.txt)
![SCR-20230804-llsb](https://github.com/watermint/toolbox/assets/597763/b1dee312-71f3-4df3-abe6-59cbd24b2e52)
![SCR-20230804-lozp](https://github.com/watermint/toolbox/assets/597763/fe608416-2874-4965-8160-65b20cabe1fb)

**Comment by watermint** [comment]
Hi @joshuascottpaul ,

Thank you for details and sorry for confusion.
The tool generates [JSONL (JSON Lines)](https://jsonlines.org/) not plain JSON.
This is by deliberate design, as handling large arrays in JSON consumes a large amount of memory and can lead to crashes or prevent processing from continuing.

Please split lines by line separator character before you parse result.

**Comment by joshuascottpaul** [comment]
awesome! thanks.

**Comment by joshuascottpaul** [comment]
there is still an issue

this command generates invalid jsonl
 /usr/bin/tbx file list -path / 

i tested it and the result is invalid jsonl

it end with }}

{".tag": "folder", "name": "neocode", "path_lower": "/neocode", "path_display": "/neocode", "id": "id:qRn4_DiJ1CkAAAAAAAAAGQ", "shared_folder_id": "10832502000", "sharing_info": {"read_only": false, "shared_folder_id": "10832502000", "traverse_only": false, "no_access": false}}


https://jsonlines.org/validator/

![SCR-20230807-kxhq](https://github.com/watermint/toolbox/assets/597763/b32d0633-410c-4a0b-87b4-71a6a41bfed3)

**Comment by watermint** [comment]
This looks like valid JSON

```
{".tag": "folder", "name": "neocode", "path_lower": "/neocode", "path_display": "/neocode", "id": "id:qRn4_DiJ1CkAAAAAAAAAGQ", "shared_folder_id": "10832502000", "sharing_info": {"read_only": false, "shared_folder_id": "10832502000", "traverse_only": false, "no_access": false}}
```

Here is the prettified version
```
{
  ".tag": "folder",
  "name": "neocode",
  "path_lower": "/neocode",
  "path_display": "/neocode",
  "id": "id:qRn4_DiJ1CkAAAAAAAAAGQ",
  "shared_folder_id": "10832502000",
  "sharing_info": {
    "read_only": false,
    "shared_folder_id": "10832502000",
    "traverse_only": false,
    "no_access": false
  }
}
```

**Comment by joshuascottpaul** [comment]
doh!! my mistake. i am so sorry. thank you for your time. :)
