### ISSUE TITLE
Access blocked by Google

### ISSUE THREAD

**Issue by geekobiloba** [watermint/toolbox#777]
**Describe the bug**

toolbox cannot authenticate with Google with the following error messages:

```
Access blocked: watermint toolbox has not completed the Google verification process

watermint toolbox has not completed the Google verification process. The app is currently being tested, and can only be accessed by developer-approved testers. If you think you should have access, contact the developer.
If you are a developer of watermint toolbox, see error details.

Error 403: access_denied
```

**To Reproduce**

1. Run either these commands,

    ```
    tbx services google calendar event list
    tbx services google sheets sheet list -id $SHEETS_ID
    ```

2. Open the link in a browser and see the error.

**Expected behavior**

The access prompt should show to grant the service access to toolbox.

**Desktop**

- OS: macOS 13.6.2 build 22G320
- toolbox Version: 123.8.79

**Comment by watermint** [comment]
Hi @geekobiloba, Thank you for raise the ticket.
I understand the situation and proceeding verification process with Google.
I'm still waiting for updates from Google.
I'll update once the issue resolved. Thanks.

**Comment by HVRyan** [comment]
Hate to be "that guy", but has google provided any updates on this yet?

**Comment by watermint** [comment]
I have no update from Google yet unfortunately.

I once reported a Google API bug, which was left unanswered for over a few months and eventually silently closed.
Google's SLA is like that, IMO.

**Comment by watermint** [comment]
The video instruction to Google have 0 views. That means, Google haven't start proceed my request yet :-(

**Comment by watermint** [comment]
I still waiting for Google's response but completely no response, no notification, nor support (even I paid a little for Workspace).
This is a bug of Google, not on my project. Thank you for understanding....

**Comment by watermint** [comment]
Since no updates from Google :-(
I decided to deprecate the existing app key and release with a new app key from the next release.
The existing app key will be removed once the migration is complete.

# Impact

* Existing users will be asked to re-authenticate with their account.
* New App Key must also pass Google verification. Google's help page says it will take 3-6 weeks to complete. But I don't trust them on the timeframe.

**Comment by HVRyan** [comment]
That is some hell they're putting you though; TY for your efforts!

**Comment by watermint** [comment]
Hello everyone in this thread,
I have released new version Release 130 which has new Google's client key.
Existing users need to re-authenticate, and new users can start using Google commands.
But this is first come first served basis up to 100 users until Google to approve my app.

**Comment by watermint** [comment]
Hi everyone,
I just decided deprecating Google commands. Please see the below announcement.
I apologise for not meeting the expectations of all those who have used the product so far.

https://github.com/watermint/toolbox/discussions/835
