### ISSUE TITLE
Add ability to append data to google sheets (not just replace)

### ISSUE THREAD

**Issue by bartmoc** [watermint/toolbox#842]
**Is your feature request related to a problem? Please describe.**
I have some sensors data in csv file, every time I run
tbx services google sheets sheet import -id .... -range Arkusz1 -data /tmp/sensors.txt

**Describe the solution you'd like**
I want the data to be appended to the sheet (don't replace existing one).
Maybe add some -append flag or sth?

**Describe alternatives you've considered**
Maybe  -range should include some mark, that points that it should append to the end???

**Comment by watermint** [comment]
Hi, thanks for writing in.
But unfortunately I have decided to deprecate all Google commands soon.

Here are the details: 
https://github.com/watermint/toolbox/discussions/835

**Comment by watermint** [comment]
By the way, here is the command to append data. You can use this command until Aug. Thanks.
https://toolbox.watermint.org/commands/google-sheets-sheet-append.html
